# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://tbaraki.net"
defaultContentLanguage = "en"

enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
